services:

  app:
    image: snipe/snipe-it:latest
    depends_on:
    - db
    volumes:
    - ./data/app:/var/lib/snipeit
    - ./data/logs:/var/www/html/storage/logs
    env_file:
    - .env
    ports:
      - "8080:80"
    restart: unless-stopped

  db:
    image: mariadb:11.5
    volumes:
    - ./data/db:/var/lib/mysql
    env_file:
    - .env
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    volumes:
      - ./data/mailhog:/var/mailhog
    restart: unless-stopped
